# Generated by Django 4.1.3 on 2022-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, unique=True)),
                ('books', models.ManyToManyField(to='store.book')),
            ],
        ),
    ]
